### ISSUE TITLE
Var<string> does not work unless string is quoted so its valid json

### ISSUE THREAD

**Issue by cmcpasserby** [CleverTap/clevertap-unity-sdk#101] opened 2024-11-29 17:48 UTC
Anytime `.Value` is read from on a `Var<string>`, the string is treated as if its json when it is not, and the Value getter on AndroidVar and IOSVar ends up just returning defaultValue instead of the modified string from the dashboard.

The cause of this is from
https://github.com/CleverTap/clevertap-unity-sdk/blob/b6a2ab393f152f8ec0759063d48954fd7002b7e5/CleverTap/Runtime/Android/AndroidVar.cs#L11-L28
and 
https://github.com/CleverTap/clevertap-unity-sdk/blob/b6a2ab393f152f8ec0759063d48954fd7002b7e5/CleverTap/Runtime/IOS/IOSVar.cs#L11-L32

Because the string is always treated as json, even know `getVariableValue` will return exactly the string provided on the dashboard and not a json object containing a string. Thus the `object newValue = Json.Deserialize(jsonRepresentation);` line always returns null causing things to always get into the branch that returns default value.

I suspect this was caused by the fix in https://github.com/CleverTap/clevertap-unity-sdk/pull/61/files where all strings used to return quoted.

**Comment by nzagorchev** [comment] 2024-12-01 15:16
Hi @cmcpasserby, we have identified this issue on Android and fixed it here #97. We have not been able to reproduce this on iOS.
How is the variable you reproduce it with on both platforms defined and what is the override on the Dashboard?

**Comment by cmcpasserby** [comment] 2024-12-01 17:25
So when is #97 expected to make it into a release, 4.0.0 seems to be latest and is in August and was merged to develop 3 weeks ago.

**Comment by nzagorchev** [comment] 2024-12-02 07:58
The current ETA is the week of 16-20 Dec depending on how QA is going. 
We are also updating CleverTap Android and iOS SDKs to 7.0.3.

Can you please let me know if you are reproducing the issue on iOS since the PR #97 only does fixes to Android? We were not able to reproduce the issue on iOS, the values come differently from the native bridge there.

**Comment by cmcpasserby** [comment] 2024-12-10 20:31
Confirmed on IOS with same project this issue does not exist, so seems its just a matter of waiting for the known fix on the android side.

**Comment by nzagorchev** [comment] 2024-12-16 15:21
Fixed with #96 and released with [4.1.0](https://github.com/CleverTap/clevertap-unity-sdk/releases/tag/4.1.0)

**Closed by nzagorchev** 2024-12-16 15:21 UTC
